services:
  postgres:
    image: postgres:14
    container_name: insurance-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: insurance
      POSTGRES_USER: insurance_user
      POSTGRES_PASSWORD: insurance_pass
    volumes:
      - insurance_pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"   # host:container -> ajustado para evitar conflito com seu postgres local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  insurance_pgdata:
