spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/insurance   # se usar o docker-compose acima
    driver-class-name: org.postgresql.Driver
    username: insurance_user
    password: insurance_pass

  jpa:
    hibernate:
      ddl-auto: update     # em dev, ok; em prod, use 'none' + migrations
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never          # evitar schema.sql/data.sql se usar JPA ou migrações

server:
  port: 8080
