spring:
  application:
    name: insurance-api

  datasource:
    url: jdbc:h2:mem:insurance;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update        # Hibernate cria e atualiza a tabela
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true  # garante execução do data.sql após o Hibernate

  sql:
    init:
      mode: always            # executa data.sql sempre

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080
